[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
account_data_matching = "7XwbyBnzDBTfq5iEp9kmeQkSsLEjeskcjCPYMhGYxhD5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sebatustra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
